In [1]:
# ニューラルネットワークの復習
# ベクトルと行列
import numpy as np

x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [2]:
x.shape

(3,)

In [3]:
x.ndim

1

In [4]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [5]:
W.ndim

2

In [6]:
 # 行列の要素ごとの演算
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [7]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [8]:
# ブロードキャスト
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [11]:
# ベクトルの内積
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a @ b

np.int64(32)

In [12]:
# 行列の積
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A @ B

array([[19, 22],
       [43, 50]])

In [13]:
# ニューラルネットワークの推論の全体図

In [15]:
# ミニバッチ版の全結合層による変換
import numpy as np

rng = np.random.default_rng()

W1 = rng.random((2, 4))
b1 = rng.random(4)
x = rng.random((10, 2))
h = x @ W1 + b1

In [17]:
# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

a = sigmoid(h)

In [18]:
# レイヤとしてのクラス化と順伝播の実装

In [19]:
# シグモイドレイヤ
import numpy as np

class Sigmoid:
    def __init__(self):
        self.params = []
    
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [20]:
# Affineレイヤ
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = x @ W + b
        return out

In [25]:
# TwoLayerNetの実装

rng = np.random.default_rng

class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 重みとバイアスの初期化
        W1 = rng.random((I, H))
        b1 = rng.random(H)
        W2 = rng.random((H, O))
        b2 = rng.random(O)

        # レイヤの生成
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 全ての重みをリストにまとめる
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


In [26]:
rng = np.random.default_rng()

x = rng.random((10, 2))
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

In [27]:
# ニューラルネットワークの学習
# 損失関数
# 微分と勾配
# チェインルール

In [30]:
# Repeatノード
import numpy as np

rng = np.random.default_rng()

D, N = 8, 7
x = rng.random((1, D))
y = np.repeat(x, N, axis=0)

dy = rng.random((N, D))
dx = np.sum(dy, axis=0, keepdims=True)

In [31]:
# Sumノード
import numpy as np

rng = np.random.default_rng()

D, N = 8, 7
x = rng.random((N, D))
y = np.sum(x, axis=0, keepdims=True)

dy = rng.random((1, D))
dx = np.repeat(dy, N, axis=0)

In [32]:
# MatMulノード
class MatMul:
    def __init__ (self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = x @ W
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = dout @ W.T
        dW = self.x.T @ dout
        self.grads[0][...] = dW
        return dx