In [1]:
# ニューラルネットワークの復習
# ベクトルと行列
import numpy as np

x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [2]:
x.shape

(3,)

In [3]:
x.ndim

1

In [4]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [5]:
W.ndim

2

In [6]:
 # 行列の要素ごとの演算
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [7]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [8]:
# ブロードキャスト
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [11]:
# ベクトルの内積
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a @ b

np.int64(32)

In [12]:
# 行列の積
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A @ B

array([[19, 22],
       [43, 50]])

In [13]:
# ニューラルネットワークの推論の全体図

In [15]:
# ミニバッチ版の全結合層による変換
import numpy as np

rng = np.random.default_rng()

W1 = rng.random((2, 4))
b1 = rng.random(4)
x = rng.random((10, 2))
h = x @ W1 + b1

In [17]:
# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

a = sigmoid(h)