In [1]:
# word2vec
# 推論ベースの手法とニューラルネットワーク
# カウントベースの手法の問題点
# 推論ベースの手法の概要
# ニューラルネットワークにおける単語の処理方法

In [2]:
import numpy as np

rng = np.random.default_rng()

c = np.array([1, 0, 0, 0, 0, 0, 0]) # 入力
W = rng.random((7, 3)) # 重み
h = c @ W
print(h)

[0.08900274 0.15961597 0.0153568 ]


In [4]:
# MutMulレイヤ
import sys
sys.path.append("..")
import numpy as np
from common.layers import MatMul

c = np.array([1, 0, 0, 0, 0, 0, 0])
W = rng.random((7, 3))
layer = MatMul(W)
h = layer.forward(c)
print(h)

[0.20449605 0.834693   0.29146379]


In [5]:
# シンプルなword2vec
# CBOWモデルの推論処理
import sys
sys.path.append("..")
import numpy as np
from common.layers import MatMul

# サンプルのコンテキストデータ
c0 = np.array([1, 0, 0, 0, 0, 0, 0])
c1 = np.array([0, 0, 1, 0, 0, 0, 0])

# 重みの初期化
W_in = rng.random((7, 3))
W_out = rng.random((3, 7))

# レイヤの生成
in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

# 順伝播
h0 = in_layer0.forward(c0)
h1 = in_layer1.forward(c1)
h = 0.5
s = out_layer.forward(h)

print(s)

[[0.24067425 0.45357123 0.07094461 0.00728961 0.3921104  0.47324839
  0.15097133]
 [0.11228092 0.30720642 0.2025431  0.28036674 0.01243242 0.24354914
  0.30049407]
 [0.45512078 0.14198103 0.30683202 0.43430411 0.15643563 0.48457304
  0.19314995]]


In [6]:
# CBOWモデルの学習
# word2vecの重みと分散表現

In [7]:
# コンテキストとターゲット
# コーパスからコンテキストとターゲットを作成する関数を実装
import sys
sys.path.append("..")
from ch02.similarity import corpus, id_to_word, word_to_id
from common.util import preprocess

text = "You say goodbye and I say hello."
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)
print(id_to_word)

0.7071067691154799
[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [9]:
from multiprocessing import context


def create_contexts_target(corpus, window_size=1):
    target = corpus[window_size:-window_size]
    contexts = []

    for idx in range(window_size, len(corpus)-window_size):
        cs = []
        for t in range(-window_size, window_size + 1):
            if t == 0:
                continue
            cs.append(corpus[idx + t])
        contexts.append(cs)

    return np.array(contexts), np.array(target)

contexts, target = create_contexts_target(corpus, window_size=1)
print(contexts)
print(target)

[[0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]
[1 2 3 4 1 5]
