In [1]:
# word2vecの高速か
# word2vecの改良

In [2]:
# Embeddingレイヤの実装
import numpy as np
W = np.arange(21).reshape(7, 3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [3]:
idx = np.array([1, 0, 3, 0])
W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [ ]:
# Embaddingレイヤのforward()メソッドを実装
class Embedding:
    def __init__ (self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out =W[idx]
        return out

In [7]:
# Embaddingライやのbackward()メソッドの実装
def backward(self, dout):
    dW = self.grads
    dW[...] = 0
    
    for i, word_id in enumerate(self, idx):
        dW[word_id] += dout[i]

        return None

In [8]:
# word2vecの改良２
# 中間層以降の計算の問題点
# 多値分類から二値分類へ
# シグモイド関数と交差エントロピー誤差

In [9]:
# 多値分類から二値分類　実装
class EmbaddingDot:
    def __init__(self, W):
        self.embed = Embedding(W)
        self.params = self.embed.grads
        self.grads = self.embed.grads
        self.cache = None

    def forward(self, h, idx):
        target_W = self.embed.forward(idx)
        out = np.sum(target_W * h, axis=1)

        self.cache = (h, target_W)
        return out

    def backward(self, dout):
        h, target_W = self.cache
        dout = dout.reshape(dout.shape[0], 1)

        dtarget_W = dout * h
        dh = dout * target_W
        return dh

In [10]:
# Negative Sampling
# Negative Samplingのサンプリング手法

In [11]:
# 確率分布に従ったサンプリング
# np.random.choice()の例
import numpy as np

# 8~9の数字の中から1つの数字をランダムにサンプリング
np.random.choice(10)

2

In [12]:
# wordsから1つだけランダムにサンプリング
words = ["you", "say", "goodbye", "I", "hello", "."]
np.random.choice(words)

np.str_('you')

In [13]:
# 5つだけランダムにサンプリング（重複あり）
np.random.choice(words, size=5)

array(['hello', '.', 'you', 'you', 'you'], dtype='<U7')

In [14]:
# 5つだけランダムサンプリング（重複なし）
np.random.choice(words, size=5, replace=False)

array(['say', '.', 'goodbye', 'hello', 'you'], dtype='<U7')

In [15]:
# 確率分布に従ってサンプリング
p = [0.5, 0.1, 0.05, 0.2, 0.05, 0.1]
np.random.choice(words, p=p)

np.str_('you')

In [16]:
p = [0.7, 0.29, 0.01]
new_p = np.power(p, 0.75)
new_p /= np.sum(new_p)
print(new_p)

[0.64196878 0.33150408 0.02652714]


In [18]:
# UnigraSamplerクラスの例
from negative_sampling_layer import UnigramSampler


corpus = np.array([0, 1, 2, 3, 4, 1, 2, 3])
power = 0.75
sample_size = 2

sampler = UnigramSampler(corpus, power, sample_size)
target = np.array([1, 3, 0])
negative_sample = sampler.get_negative_sample(target)
print(negative_sample)

[[0 2]
 [1 0]
 [3 1]]
